---
  - hosts: kali
    vars_prompt:

    - name: username
      prompt: username?
      private: no

    - name: password
      prompt: password?
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7

    tasks:
 
    - name: Print msg
      ansible.builtin.debug:
         msg: "Creating user:  {{ username }}"

    - name: Add User
      ansible.builtin.user: 
       name: "{{ username }}"
       password: "{{ password }}"
       groups: sudo 
       append: yes
